import type { Metadata } from "next";
import { Sansita } from "next/font/google";
import "./globals.css";

const sansita = Sansita({ subsets: ["latin"], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "Pets&Tips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${sansita.className}`}>{children}</body>
    </html>
  );
}
